name: Terraform Apply
#trigger test deployment
on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-southeast-1

jobs:
  Terraform-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

# Added by CY

      - name: Snyk Security Scan
        on: [push, pull_request]
        jobs:
         security:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run Snyk scan
          uses: snyk/actions/node@master
          with:
            token: ${{ secrets.SNYK_TOKEN }}
            project-name: ${{ github.ce8-grp4-app }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
# End of code
